/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as dashboardDashboardLayoutRouteImport } from './routes/(dashboard)/_dashboardLayout'
import { Route as AuthAuthLayoutRegisterRouteImport } from './routes/auth/_authLayout.register'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_authLayout.login'
import { Route as dashboardDashboardLayoutQuizzesRouteImport } from './routes/(dashboard)/_dashboardLayout.quizzes'
import { Route as dashboardDashboardLayoutQuizNewRouteImport } from './routes/(dashboard)/_dashboardLayout.quiz.new'
import { Route as dashboardDashboardLayoutQuizEditQuizIdRouteImport } from './routes/(dashboard)/_dashboardLayout.quiz.edit.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_authLayout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardLayoutRoute =
  dashboardDashboardLayoutRouteImport.update({
    id: '/(dashboard)/_dashboardLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const dashboardDashboardLayoutQuizzesRoute =
  dashboardDashboardLayoutQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutQuizNewRoute =
  dashboardDashboardLayoutQuizNewRouteImport.update({
    id: '/quiz/new',
    path: '/quiz/new',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutQuizEditQuizIdRoute =
  dashboardDashboardLayoutQuizEditQuizIdRouteImport.update({
    id: '/quiz/edit/$quizId',
    path: '/quiz/edit/$quizId',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/quizzes': typeof dashboardDashboardLayoutQuizzesRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof dashboardDashboardLayoutQuizNewRoute
  '/quiz/edit/$quizId': typeof dashboardDashboardLayoutQuizEditQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/quizzes': typeof dashboardDashboardLayoutQuizzesRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof dashboardDashboardLayoutQuizNewRoute
  '/quiz/edit/$quizId': typeof dashboardDashboardLayoutQuizEditQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/_dashboardLayout': typeof dashboardDashboardLayoutRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/(dashboard)/_dashboardLayout/quizzes': typeof dashboardDashboardLayoutQuizzesRoute
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
  '/(dashboard)/_dashboardLayout/quiz/new': typeof dashboardDashboardLayoutQuizNewRoute
  '/(dashboard)/_dashboardLayout/quiz/edit/$quizId': typeof dashboardDashboardLayoutQuizEditQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/quizzes'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/quiz/edit/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quizzes'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/quiz/edit/$quizId'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/_dashboardLayout'
    | '/auth/_authLayout'
    | '/(dashboard)/_dashboardLayout/quizzes'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
    | '/(dashboard)/_dashboardLayout/quiz/new'
    | '/(dashboard)/_dashboardLayout/quiz/edit/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardDashboardLayoutRoute: typeof dashboardDashboardLayoutRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboardLayout': {
      id: '/(dashboard)/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/quizzes': {
      id: '/(dashboard)/_dashboardLayout/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof dashboardDashboardLayoutQuizzesRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/quiz/new': {
      id: '/(dashboard)/_dashboardLayout/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof dashboardDashboardLayoutQuizNewRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/quiz/edit/$quizId': {
      id: '/(dashboard)/_dashboardLayout/quiz/edit/$quizId'
      path: '/quiz/edit/$quizId'
      fullPath: '/quiz/edit/$quizId'
      preLoaderRoute: typeof dashboardDashboardLayoutQuizEditQuizIdRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
  }
}

interface dashboardDashboardLayoutRouteChildren {
  dashboardDashboardLayoutQuizzesRoute: typeof dashboardDashboardLayoutQuizzesRoute
  dashboardDashboardLayoutQuizNewRoute: typeof dashboardDashboardLayoutQuizNewRoute
  dashboardDashboardLayoutQuizEditQuizIdRoute: typeof dashboardDashboardLayoutQuizEditQuizIdRoute
}

const dashboardDashboardLayoutRouteChildren: dashboardDashboardLayoutRouteChildren =
  {
    dashboardDashboardLayoutQuizzesRoute: dashboardDashboardLayoutQuizzesRoute,
    dashboardDashboardLayoutQuizNewRoute: dashboardDashboardLayoutQuizNewRoute,
    dashboardDashboardLayoutQuizEditQuizIdRoute:
      dashboardDashboardLayoutQuizEditQuizIdRoute,
  }

const dashboardDashboardLayoutRouteWithChildren =
  dashboardDashboardLayoutRoute._addFileChildren(
    dashboardDashboardLayoutRouteChildren,
  )

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardDashboardLayoutRoute: dashboardDashboardLayoutRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
