/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appAppLayoutRouteImport } from './routes/(app)/_appLayout'
import { Route as gameGameLayoutRouteImport } from './routes/(game)/_gameLayout'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as appAppLayoutHistoryRouteImport } from './routes/(app)/_appLayout.history'
import { Route as appAppLayoutProfileRouteImport } from './routes/(app)/_appLayout.profile'
import { Route as appAppLayoutQuizzesRouteImport } from './routes/(app)/_appLayout.quizzes'
import { Route as appAppLayoutStatsRouteImport } from './routes/(app)/_appLayout.stats'
import { Route as gameGameLayoutJoinRouteImport } from './routes/(game)/_gameLayout.join'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_authLayout.login'
import { Route as AuthAuthLayoutRegisterRouteImport } from './routes/auth/_authLayout.register'
import { Route as appAppLayoutQuizNewRouteImport } from './routes/(app)/_appLayout.quiz.new'
import { Route as gameGameLayoutHostRoomCodeRouteImport } from './routes/(game)/_gameLayout.host.$roomCode'
import { Route as gameGameLayoutPlayRoomCodeRouteImport } from './routes/(game)/_gameLayout.play.$roomCode'
import { Route as appAppLayoutQuizEditQuizIdRouteImport } from './routes/(app)/_appLayout.quiz.edit.$quizId'
import { Route as appAppLayoutQuizSetupQuizIdRouteImport } from './routes/(app)/_appLayout.quiz.setup.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppLayoutRoute = appAppLayoutRouteImport.update({
  id: '/(app)/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const gameGameLayoutRoute = gameGameLayoutRouteImport.update({
  id: '/(game)/_gameLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_authLayout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppLayoutHistoryRoute = appAppLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutProfileRoute = appAppLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutQuizzesRoute = appAppLayoutQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutStatsRoute = appAppLayoutStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const gameGameLayoutJoinRoute = gameGameLayoutJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => gameGameLayoutRoute,
} as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const appAppLayoutQuizNewRoute = appAppLayoutQuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const gameGameLayoutHostRoomCodeRoute =
  gameGameLayoutHostRoomCodeRouteImport.update({
    id: '/host/$roomCode',
    path: '/host/$roomCode',
    getParentRoute: () => gameGameLayoutRoute,
  } as any)
const gameGameLayoutPlayRoomCodeRoute =
  gameGameLayoutPlayRoomCodeRouteImport.update({
    id: '/play/$roomCode',
    path: '/play/$roomCode',
    getParentRoute: () => gameGameLayoutRoute,
  } as any)
const appAppLayoutQuizEditQuizIdRoute =
  appAppLayoutQuizEditQuizIdRouteImport.update({
    id: '/quiz/edit/$quizId',
    path: '/quiz/edit/$quizId',
    getParentRoute: () => appAppLayoutRoute,
  } as any)
const appAppLayoutQuizSetupQuizIdRoute =
  appAppLayoutQuizSetupQuizIdRouteImport.update({
    id: '/quiz/setup/$quizId',
    path: '/quiz/setup/$quizId',
    getParentRoute: () => appAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/history': typeof appAppLayoutHistoryRoute
  '/profile': typeof appAppLayoutProfileRoute
  '/quizzes': typeof appAppLayoutQuizzesRoute
  '/stats': typeof appAppLayoutStatsRoute
  '/join': typeof gameGameLayoutJoinRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof appAppLayoutQuizNewRoute
  '/host/$roomCode': typeof gameGameLayoutHostRoomCodeRoute
  '/play/$roomCode': typeof gameGameLayoutPlayRoomCodeRoute
  '/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
  '/quiz/setup/$quizId': typeof appAppLayoutQuizSetupQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/history': typeof appAppLayoutHistoryRoute
  '/profile': typeof appAppLayoutProfileRoute
  '/quizzes': typeof appAppLayoutQuizzesRoute
  '/stats': typeof appAppLayoutStatsRoute
  '/join': typeof gameGameLayoutJoinRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof appAppLayoutQuizNewRoute
  '/host/$roomCode': typeof gameGameLayoutHostRoomCodeRoute
  '/play/$roomCode': typeof gameGameLayoutPlayRoomCodeRoute
  '/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
  '/quiz/setup/$quizId': typeof appAppLayoutQuizSetupQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_appLayout': typeof appAppLayoutRouteWithChildren
  '/(game)/_gameLayout': typeof gameGameLayoutRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/(app)/_appLayout/history': typeof appAppLayoutHistoryRoute
  '/(app)/_appLayout/profile': typeof appAppLayoutProfileRoute
  '/(app)/_appLayout/quizzes': typeof appAppLayoutQuizzesRoute
  '/(app)/_appLayout/stats': typeof appAppLayoutStatsRoute
  '/(game)/_gameLayout/join': typeof gameGameLayoutJoinRoute
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
  '/(app)/_appLayout/quiz/new': typeof appAppLayoutQuizNewRoute
  '/(game)/_gameLayout/host/$roomCode': typeof gameGameLayoutHostRoomCodeRoute
  '/(game)/_gameLayout/play/$roomCode': typeof gameGameLayoutPlayRoomCodeRoute
  '/(app)/_appLayout/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
  '/(app)/_appLayout/quiz/setup/$quizId': typeof appAppLayoutQuizSetupQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/quizzes'
    | '/stats'
    | '/join'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/host/$roomCode'
    | '/play/$roomCode'
    | '/quiz/edit/$quizId'
    | '/quiz/setup/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/profile'
    | '/quizzes'
    | '/stats'
    | '/join'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/host/$roomCode'
    | '/play/$roomCode'
    | '/quiz/edit/$quizId'
    | '/quiz/setup/$quizId'
  id:
    | '__root__'
    | '/'
    | '/(app)/_appLayout'
    | '/(game)/_gameLayout'
    | '/auth/_authLayout'
    | '/(app)/_appLayout/history'
    | '/(app)/_appLayout/profile'
    | '/(app)/_appLayout/quizzes'
    | '/(app)/_appLayout/stats'
    | '/(game)/_gameLayout/join'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
    | '/(app)/_appLayout/quiz/new'
    | '/(game)/_gameLayout/host/$roomCode'
    | '/(game)/_gameLayout/play/$roomCode'
    | '/(app)/_appLayout/quiz/edit/$quizId'
    | '/(app)/_appLayout/quiz/setup/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAppLayoutRoute: typeof appAppLayoutRouteWithChildren
  gameGameLayoutRoute: typeof gameGameLayoutRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_appLayout': {
      id: '/(app)/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(game)/_gameLayout': {
      id: '/(game)/_gameLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof gameGameLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_appLayout/history': {
      id: '/(app)/_appLayout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof appAppLayoutHistoryRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/profile': {
      id: '/(app)/_appLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appAppLayoutProfileRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/quizzes': {
      id: '/(app)/_appLayout/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof appAppLayoutQuizzesRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/stats': {
      id: '/(app)/_appLayout/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof appAppLayoutStatsRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(game)/_gameLayout/join': {
      id: '/(game)/_gameLayout/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof gameGameLayoutJoinRouteImport
      parentRoute: typeof gameGameLayoutRoute
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/(app)/_appLayout/quiz/new': {
      id: '/(app)/_appLayout/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof appAppLayoutQuizNewRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(game)/_gameLayout/host/$roomCode': {
      id: '/(game)/_gameLayout/host/$roomCode'
      path: '/host/$roomCode'
      fullPath: '/host/$roomCode'
      preLoaderRoute: typeof gameGameLayoutHostRoomCodeRouteImport
      parentRoute: typeof gameGameLayoutRoute
    }
    '/(game)/_gameLayout/play/$roomCode': {
      id: '/(game)/_gameLayout/play/$roomCode'
      path: '/play/$roomCode'
      fullPath: '/play/$roomCode'
      preLoaderRoute: typeof gameGameLayoutPlayRoomCodeRouteImport
      parentRoute: typeof gameGameLayoutRoute
    }
    '/(app)/_appLayout/quiz/edit/$quizId': {
      id: '/(app)/_appLayout/quiz/edit/$quizId'
      path: '/quiz/edit/$quizId'
      fullPath: '/quiz/edit/$quizId'
      preLoaderRoute: typeof appAppLayoutQuizEditQuizIdRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/quiz/setup/$quizId': {
      id: '/(app)/_appLayout/quiz/setup/$quizId'
      path: '/quiz/setup/$quizId'
      fullPath: '/quiz/setup/$quizId'
      preLoaderRoute: typeof appAppLayoutQuizSetupQuizIdRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
  }
}

interface appAppLayoutRouteChildren {
  appAppLayoutHistoryRoute: typeof appAppLayoutHistoryRoute
  appAppLayoutProfileRoute: typeof appAppLayoutProfileRoute
  appAppLayoutQuizzesRoute: typeof appAppLayoutQuizzesRoute
  appAppLayoutStatsRoute: typeof appAppLayoutStatsRoute
  appAppLayoutQuizNewRoute: typeof appAppLayoutQuizNewRoute
  appAppLayoutQuizEditQuizIdRoute: typeof appAppLayoutQuizEditQuizIdRoute
  appAppLayoutQuizSetupQuizIdRoute: typeof appAppLayoutQuizSetupQuizIdRoute
}

const appAppLayoutRouteChildren: appAppLayoutRouteChildren = {
  appAppLayoutHistoryRoute: appAppLayoutHistoryRoute,
  appAppLayoutProfileRoute: appAppLayoutProfileRoute,
  appAppLayoutQuizzesRoute: appAppLayoutQuizzesRoute,
  appAppLayoutStatsRoute: appAppLayoutStatsRoute,
  appAppLayoutQuizNewRoute: appAppLayoutQuizNewRoute,
  appAppLayoutQuizEditQuizIdRoute: appAppLayoutQuizEditQuizIdRoute,
  appAppLayoutQuizSetupQuizIdRoute: appAppLayoutQuizSetupQuizIdRoute,
}

const appAppLayoutRouteWithChildren = appAppLayoutRoute._addFileChildren(
  appAppLayoutRouteChildren,
)

interface gameGameLayoutRouteChildren {
  gameGameLayoutJoinRoute: typeof gameGameLayoutJoinRoute
  gameGameLayoutHostRoomCodeRoute: typeof gameGameLayoutHostRoomCodeRoute
  gameGameLayoutPlayRoomCodeRoute: typeof gameGameLayoutPlayRoomCodeRoute
}

const gameGameLayoutRouteChildren: gameGameLayoutRouteChildren = {
  gameGameLayoutJoinRoute: gameGameLayoutJoinRoute,
  gameGameLayoutHostRoomCodeRoute: gameGameLayoutHostRoomCodeRoute,
  gameGameLayoutPlayRoomCodeRoute: gameGameLayoutPlayRoomCodeRoute,
}

const gameGameLayoutRouteWithChildren = gameGameLayoutRoute._addFileChildren(
  gameGameLayoutRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAppLayoutRoute: appAppLayoutRouteWithChildren,
  gameGameLayoutRoute: gameGameLayoutRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
