/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as appAppLayoutRouteImport } from './routes/(app)/_appLayout'
import { Route as AuthAuthLayoutRegisterRouteImport } from './routes/auth/_authLayout.register'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_authLayout.login'
import { Route as appAppLayoutQuizzesRouteImport } from './routes/(app)/_appLayout.quizzes'
import { Route as appAppLayoutQuizNewRouteImport } from './routes/(app)/_appLayout.quiz.new'
import { Route as appAppLayoutQuizEditQuizIdRouteImport } from './routes/(app)/_appLayout.quiz.edit.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_authLayout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppLayoutRoute = appAppLayoutRouteImport.update({
  id: '/(app)/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const appAppLayoutQuizzesRoute = appAppLayoutQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutQuizNewRoute = appAppLayoutQuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => appAppLayoutRoute,
} as any)
const appAppLayoutQuizEditQuizIdRoute =
  appAppLayoutQuizEditQuizIdRouteImport.update({
    id: '/quiz/edit/$quizId',
    path: '/quiz/edit/$quizId',
    getParentRoute: () => appAppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/quizzes': typeof appAppLayoutQuizzesRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof appAppLayoutQuizNewRoute
  '/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/quizzes': typeof appAppLayoutQuizzesRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/quiz/new': typeof appAppLayoutQuizNewRoute
  '/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/_appLayout': typeof appAppLayoutRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/(app)/_appLayout/quizzes': typeof appAppLayoutQuizzesRoute
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
  '/(app)/_appLayout/quiz/new': typeof appAppLayoutQuizNewRoute
  '/(app)/_appLayout/quiz/edit/$quizId': typeof appAppLayoutQuizEditQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/quizzes'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/quiz/edit/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quizzes'
    | '/auth/login'
    | '/auth/register'
    | '/quiz/new'
    | '/quiz/edit/$quizId'
  id:
    | '__root__'
    | '/'
    | '/(app)/_appLayout'
    | '/auth/_authLayout'
    | '/(app)/_appLayout/quizzes'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
    | '/(app)/_appLayout/quiz/new'
    | '/(app)/_appLayout/quiz/edit/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAppLayoutRoute: typeof appAppLayoutRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_appLayout': {
      id: '/(app)/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/(app)/_appLayout/quizzes': {
      id: '/(app)/_appLayout/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof appAppLayoutQuizzesRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/quiz/new': {
      id: '/(app)/_appLayout/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof appAppLayoutQuizNewRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
    '/(app)/_appLayout/quiz/edit/$quizId': {
      id: '/(app)/_appLayout/quiz/edit/$quizId'
      path: '/quiz/edit/$quizId'
      fullPath: '/quiz/edit/$quizId'
      preLoaderRoute: typeof appAppLayoutQuizEditQuizIdRouteImport
      parentRoute: typeof appAppLayoutRoute
    }
  }
}

interface appAppLayoutRouteChildren {
  appAppLayoutQuizzesRoute: typeof appAppLayoutQuizzesRoute
  appAppLayoutQuizNewRoute: typeof appAppLayoutQuizNewRoute
  appAppLayoutQuizEditQuizIdRoute: typeof appAppLayoutQuizEditQuizIdRoute
}

const appAppLayoutRouteChildren: appAppLayoutRouteChildren = {
  appAppLayoutQuizzesRoute: appAppLayoutQuizzesRoute,
  appAppLayoutQuizNewRoute: appAppLayoutQuizNewRoute,
  appAppLayoutQuizEditQuizIdRoute: appAppLayoutQuizEditQuizIdRoute,
}

const appAppLayoutRouteWithChildren = appAppLayoutRoute._addFileChildren(
  appAppLayoutRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAppLayoutRoute: appAppLayoutRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
